env:
    browser: true
    es2021: true
    node: true
extends:
    - eslint:recommended
    - plugin:react/recommended
overrides: []
parserOptions:
    ecmaVersion: latest
plugins:
    - react
rules:
    {
        'indent': ['error', 4],
        'object-curly-spacing': ['error', 'always'],
        'operator-linebreak': ['error', 'before'],
        'comma-dangle':
            [
                'error',
                {
                    'arrays': 'always-multiline',
                    'objects': 'always-multiline',
                    'imports': 'always-multiline',
                    'exports': 'always-multiline',
                    'functions': never,
                },
            ],
        'linebreak-style': ['error', 'windows'],
    }
